language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t desmond1999d/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true desmond1999d/docker-react npm run test
deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "artur"
    env: "Artur-env"
    bucket_name: "elasticbeanstalk-eu-central-1-265438726114"
    bucket_path: "artur"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY